from __future__ import annotations

from typing import Any

from app.shared.core.pricing_types import FeatureFlag, FeatureMaturity, PricingTier

__all__ = [
    "TIER_CONFIG",
    "ENTERPRISE_FEATURES",
    "FEATURE_MATURITY",
]

# Explicit enterprise entitlement roster (curated, non-dynamic).
# Keep this list intentionally explicit so new FeatureFlag additions do not
# auto-promote into Enterprise without an explicit packaging decision.
ENTERPRISE_FEATURES: set[FeatureFlag] = {
    FeatureFlag.DASHBOARDS,
    FeatureFlag.COST_TRACKING,
    FeatureFlag.ALERTS,
    FeatureFlag.SLACK_INTEGRATION,
    FeatureFlag.ZOMBIE_SCAN,
    FeatureFlag.LLM_ANALYSIS,
    FeatureFlag.AI_INSIGHTS,
    FeatureFlag.MULTI_CLOUD,
    FeatureFlag.MULTI_REGION,
    FeatureFlag.GREENOPS,
    FeatureFlag.CARBON_TRACKING,
    FeatureFlag.AUTO_REMEDIATION,
    FeatureFlag.API_ACCESS,
    FeatureFlag.FORECASTING,
    FeatureFlag.SSO,
    FeatureFlag.SCIM,
    FeatureFlag.DEDICATED_SUPPORT,
    FeatureFlag.AUDIT_LOGS,
    FeatureFlag.HOURLY_SCANS,
    FeatureFlag.AI_ANALYSIS_DETAILED,
    FeatureFlag.DOMAIN_DISCOVERY,
    FeatureFlag.IDP_DEEP_SCAN,
    FeatureFlag.PRECISION_DISCOVERY,
    FeatureFlag.OWNER_ATTRIBUTION,
    FeatureFlag.GITOPS_REMEDIATION,
    FeatureFlag.UNIT_ECONOMICS,
    FeatureFlag.INGESTION_SLA,
    FeatureFlag.INGESTION_BACKFILL,
    FeatureFlag.ANOMALY_DETECTION,
    FeatureFlag.CHARGEBACK,
    FeatureFlag.RECONCILIATION,
    FeatureFlag.CLOSE_WORKFLOW,
    FeatureFlag.CARBON_ASSURANCE,
    FeatureFlag.CLOUD_PLUS_CONNECTORS,
    FeatureFlag.COMPLIANCE_EXPORTS,
    FeatureFlag.SAVINGS_PROOF,
    FeatureFlag.COMMITMENT_OPTIMIZATION,
    FeatureFlag.POLICY_PREVIEW,
    FeatureFlag.POLICY_CONFIGURATION,
    FeatureFlag.ESCALATION_WORKFLOW,
    FeatureFlag.INCIDENT_INTEGRATIONS,
}

# Runtime-gated features are mapped to GA maturity.
# Catalog-only (not yet hard-gated) features are explicitly tracked in Preview.
_RUNTIME_GATED_FEATURES: set[FeatureFlag] = {
    FeatureFlag.COST_TRACKING,
    FeatureFlag.SLACK_INTEGRATION,
    FeatureFlag.LLM_ANALYSIS,
    FeatureFlag.GREENOPS,
    FeatureFlag.AUTO_REMEDIATION,
    FeatureFlag.SSO,
    FeatureFlag.SCIM,
    FeatureFlag.AUDIT_LOGS,
    FeatureFlag.IDP_DEEP_SCAN,
    FeatureFlag.PRECISION_DISCOVERY,
    FeatureFlag.OWNER_ATTRIBUTION,
    FeatureFlag.GITOPS_REMEDIATION,
    FeatureFlag.UNIT_ECONOMICS,
    FeatureFlag.INGESTION_SLA,
    FeatureFlag.INGESTION_BACKFILL,
    FeatureFlag.ANOMALY_DETECTION,
    FeatureFlag.CHARGEBACK,
    FeatureFlag.RECONCILIATION,
    FeatureFlag.CLOSE_WORKFLOW,
    FeatureFlag.CARBON_ASSURANCE,
    FeatureFlag.CLOUD_PLUS_CONNECTORS,
    FeatureFlag.COMPLIANCE_EXPORTS,
    FeatureFlag.SAVINGS_PROOF,
    FeatureFlag.COMMITMENT_OPTIMIZATION,
    FeatureFlag.POLICY_PREVIEW,
    FeatureFlag.ESCALATION_WORKFLOW,
    FeatureFlag.INCIDENT_INTEGRATIONS,
}

_PREVIEW_MATURITY_FEATURES: set[FeatureFlag] = {
    FeatureFlag.DASHBOARDS,
    FeatureFlag.ALERTS,
    FeatureFlag.ZOMBIE_SCAN,
    FeatureFlag.AI_INSIGHTS,
    FeatureFlag.DOMAIN_DISCOVERY,
    FeatureFlag.MULTI_CLOUD,
    FeatureFlag.MULTI_REGION,
    FeatureFlag.CARBON_TRACKING,
    FeatureFlag.API_ACCESS,
    FeatureFlag.DEDICATED_SUPPORT,
    FeatureFlag.HOURLY_SCANS,
    FeatureFlag.AI_ANALYSIS_DETAILED,
    FeatureFlag.FORECASTING,
    FeatureFlag.POLICY_CONFIGURATION,
}

_FEATURE_MATURITY_COVERAGE = _RUNTIME_GATED_FEATURES | _PREVIEW_MATURITY_FEATURES
_ALL_FEATURE_FLAGS = {flag for flag in FeatureFlag}
_FEATURE_MATURITY_MISSING = _ALL_FEATURE_FLAGS - _FEATURE_MATURITY_COVERAGE
_FEATURE_MATURITY_EXTRA = _FEATURE_MATURITY_COVERAGE - _ALL_FEATURE_FLAGS
if _FEATURE_MATURITY_MISSING or _FEATURE_MATURITY_EXTRA:
    raise RuntimeError(
        "Feature maturity classification is incomplete or invalid. "
        f"missing={[item.value for item in sorted(_FEATURE_MATURITY_MISSING, key=lambda x: x.value)]} "
        f"extra={[item.value for item in sorted(_FEATURE_MATURITY_EXTRA, key=lambda x: x.value)]}"
    )

FEATURE_MATURITY: dict[FeatureFlag, FeatureMaturity] = {
    flag: (
        FeatureMaturity.GA
        if flag in _RUNTIME_GATED_FEATURES
        else FeatureMaturity.PREVIEW
    )
    for flag in FeatureFlag
}

# Tier configuration - USD pricing
TIER_CONFIG: dict[PricingTier, dict[str, Any]] = {
    PricingTier.FREE: {
        "name": "Free",
        "price_usd": 0,
        "features": {
            FeatureFlag.DASHBOARDS,
            FeatureFlag.COST_TRACKING,
            FeatureFlag.ALERTS,
            FeatureFlag.ZOMBIE_SCAN,
            FeatureFlag.LLM_ANALYSIS,
            FeatureFlag.DOMAIN_DISCOVERY,
            FeatureFlag.GREENOPS,
            FeatureFlag.CARBON_TRACKING,
            FeatureFlag.UNIT_ECONOMICS,
        },
        "limits": {
            "max_aws_accounts": 1,
            "max_azure_tenants": 0,
            "max_gcp_projects": 0,
            "max_saas_connections": 0,
            "max_license_connections": 0,
            "max_platform_connections": 0,
            "max_hybrid_connections": 0,
            "byok_enabled": True,
            "ai_insights_per_month": 0,
            "scan_frequency_hours": 168,
            "zombie_scans_per_day": 1,
            "llm_analyses_per_day": 1,
            "llm_analyses_per_user_per_day": 1,
            "llm_system_analyses_per_day": 1,
            "llm_analysis_max_records": 128,
            "llm_analysis_max_window_days": 31,
            "llm_prompt_max_input_tokens": 2048,
            "llm_output_max_tokens": 512,
            "max_backfill_days": 0,
            "retention_days": 30,
        },
        "description": "Permanent free plan with core FinOps visibility and capped AI usage.",
        "cta": "Start Free",
        "display_features": [
            "Single cloud provider (AWS) + core dashboards",
            "Weekly zombie scans + basic alerts",
            "1 AI analysis/day",
            "BYOK supported (no platform surcharge)",
            "30-day data retention",
            "Entry-tier limits with no credit card",
        ],
    },
    PricingTier.STARTER: {
        "name": "Starter",
        "price_usd": {"monthly": 49, "annual": 490},
        "features": {
            FeatureFlag.DASHBOARDS,
            FeatureFlag.COST_TRACKING,
            FeatureFlag.ALERTS,
            FeatureFlag.ZOMBIE_SCAN,
            FeatureFlag.AI_INSIGHTS,
            FeatureFlag.LLM_ANALYSIS,
            FeatureFlag.DOMAIN_DISCOVERY,
            FeatureFlag.MULTI_REGION,
            FeatureFlag.CARBON_TRACKING,
            FeatureFlag.GREENOPS,
            FeatureFlag.UNIT_ECONOMICS,
            FeatureFlag.INGESTION_SLA,
        },
        "limits": {
            "max_aws_accounts": 5,
            "max_azure_tenants": 0,
            "max_gcp_projects": 0,
            "max_saas_connections": 0,
            "max_license_connections": 0,
            "max_platform_connections": 0,
            "max_hybrid_connections": 0,
            "byok_enabled": True,
            "ai_insights_per_month": 10,
            "llm_analyses_per_day": 5,
            "llm_analyses_per_user_per_day": 2,
            "llm_system_analyses_per_day": 2,
            "llm_analysis_max_records": 256,
            "llm_analysis_max_window_days": 90,
            "llm_prompt_max_input_tokens": 4096,
            "llm_output_max_tokens": 1024,
            "max_backfill_days": 0,
            "scan_frequency_hours": 24,
            "retention_days": 90,
        },
        "description": "For small teams getting started with cloud cost visibility.",
        "cta": "Start with Starter",
        "display_features": [
            "Includes all Free features",
            "Multi-account support",
            "Advanced budget alerts",
            "5 AI analyses/day",
            "BYOK supported (no platform surcharge)",
            "Unit economics KPIs + ingestion SLA monitor",
            "Multi-region analysis",
            "90-day data retention",
        ],
    },
    PricingTier.GROWTH: {
        "name": "Growth",
        "price_usd": {"monthly": 149, "annual": 1490},
        "features": {
            FeatureFlag.DASHBOARDS,
            FeatureFlag.COST_TRACKING,
            FeatureFlag.ALERTS,
            FeatureFlag.ZOMBIE_SCAN,
            FeatureFlag.AI_INSIGHTS,
            FeatureFlag.LLM_ANALYSIS,
            FeatureFlag.DOMAIN_DISCOVERY,
            FeatureFlag.MULTI_CLOUD,
            FeatureFlag.MULTI_REGION,
            FeatureFlag.CARBON_TRACKING,
            FeatureFlag.GREENOPS,
            FeatureFlag.AUTO_REMEDIATION,
            FeatureFlag.PRECISION_DISCOVERY,
            FeatureFlag.OWNER_ATTRIBUTION,
            FeatureFlag.CHARGEBACK,
            FeatureFlag.INGESTION_SLA,
            FeatureFlag.INGESTION_BACKFILL,
            FeatureFlag.ANOMALY_DETECTION,
            FeatureFlag.UNIT_ECONOMICS,
            FeatureFlag.POLICY_PREVIEW,
            FeatureFlag.ESCALATION_WORKFLOW,
            FeatureFlag.COMMITMENT_OPTIMIZATION,
        },
        "limits": {
            "max_aws_accounts": 20,
            "max_azure_tenants": 10,
            "max_gcp_projects": 15,
            "max_saas_connections": 0,
            "max_license_connections": 0,
            "max_platform_connections": 0,
            "max_hybrid_connections": 0,
            "byok_enabled": True,
            "llm_analyses_per_day": 20,
            "llm_analyses_per_user_per_day": 8,
            "llm_system_analyses_per_day": 5,
            "llm_analysis_max_records": 1024,
            "llm_analysis_max_window_days": 365,
            "llm_prompt_max_input_tokens": 12288,
            "llm_output_max_tokens": 2048,
            "max_backfill_days": 180,
            "retention_days": 365,
        },
        "description": "For growing teams who need structured FinOps governance.",
        "cta": "Start with Growth",
        "display_features": [
            "Includes all Starter features",
            "AI-driven savings analyses",
            "Chargeback/showback workflows",
            "Historical ingestion backfill",
            "Non-production auto-remediation workflows",
            "BYOK supported (no platform surcharge)",
            "Full multi-cloud support",
            "1-year data retention",
        ],
    },
    PricingTier.PRO: {
        "name": "Pro",
        "price_usd": {"monthly": 299, "annual": 2990},
        "features": {
            FeatureFlag.DASHBOARDS,
            FeatureFlag.COST_TRACKING,
            FeatureFlag.ALERTS,
            FeatureFlag.ZOMBIE_SCAN,
            FeatureFlag.AI_INSIGHTS,
            FeatureFlag.LLM_ANALYSIS,
            FeatureFlag.DOMAIN_DISCOVERY,
            FeatureFlag.IDP_DEEP_SCAN,
            FeatureFlag.MULTI_CLOUD,
            FeatureFlag.MULTI_REGION,
            FeatureFlag.CARBON_TRACKING,
            FeatureFlag.GREENOPS,
            FeatureFlag.AUTO_REMEDIATION,
            FeatureFlag.SSO,
            FeatureFlag.API_ACCESS,
            FeatureFlag.DEDICATED_SUPPORT,
            FeatureFlag.HOURLY_SCANS,
            FeatureFlag.AI_ANALYSIS_DETAILED,
            FeatureFlag.SLACK_INTEGRATION,
            FeatureFlag.AUDIT_LOGS,
            FeatureFlag.GITOPS_REMEDIATION,
            FeatureFlag.PRECISION_DISCOVERY,
            FeatureFlag.OWNER_ATTRIBUTION,
            FeatureFlag.CHARGEBACK,
            FeatureFlag.INGESTION_SLA,
            FeatureFlag.INGESTION_BACKFILL,
            FeatureFlag.ANOMALY_DETECTION,
            FeatureFlag.UNIT_ECONOMICS,
            FeatureFlag.RECONCILIATION,
            FeatureFlag.CLOSE_WORKFLOW,
            FeatureFlag.CARBON_ASSURANCE,
            FeatureFlag.CLOUD_PLUS_CONNECTORS,
            FeatureFlag.COMPLIANCE_EXPORTS,
            FeatureFlag.SAVINGS_PROOF,
            FeatureFlag.COMMITMENT_OPTIMIZATION,
            FeatureFlag.POLICY_PREVIEW,
            FeatureFlag.POLICY_CONFIGURATION,
            FeatureFlag.ESCALATION_WORKFLOW,
            FeatureFlag.INCIDENT_INTEGRATIONS,
        },
        "limits": {
            "max_aws_accounts": 25,
            "max_azure_tenants": 25,
            "max_gcp_projects": 25,
            "max_saas_connections": 10,
            "max_license_connections": 10,
            "max_platform_connections": 10,
            "max_hybrid_connections": 10,
            "byok_enabled": True,
            "ai_insights_per_month": 100,
            "llm_analyses_per_day": 100,
            "llm_analyses_per_user_per_day": 25,
            "llm_system_analyses_per_day": 30,
            "llm_analysis_max_records": 5000,
            "llm_analysis_max_window_days": 730,
            "llm_prompt_max_input_tokens": 32768,
            "llm_output_max_tokens": 4096,
            "max_backfill_days": 730,
            "scan_frequency_hours": 1,
            "retention_days": 730,
        },
        "description": "For enterprises requiring high-scale cloud governance.",
        "cta": "Contact Sales",
        "display_features": [
            "Includes all Growth features",
            "SSO / SAML integration",
            "Hourly zombie scanning",
            "Finance-grade reconciliation + close workflow",
            "Dedicated support engineer",
            "Compliance exports and audit evidence",
            "Custom GitOps remediation",
            "BYOK supported (no platform surcharge)",
        ],
    },
    PricingTier.ENTERPRISE: {
        "name": "Enterprise",
        "price_usd": None,
        "features": ENTERPRISE_FEATURES,
        "limits": {
            "max_aws_accounts": 999,
            "max_azure_tenants": 999,
            "max_gcp_projects": 999,
            "max_saas_connections": 999,
            "max_license_connections": 999,
            "max_platform_connections": 999,
            "max_hybrid_connections": 999,
            "byok_enabled": True,
            "ai_insights_per_month": 999,
            "llm_analyses_per_day": 2000,
            "llm_analyses_per_user_per_day": 500,
            "llm_system_analyses_per_day": 400,
            "llm_analysis_max_records": 20000,
            "llm_analysis_max_window_days": 3650,
            "llm_prompt_max_input_tokens": 65536,
            "llm_output_max_tokens": 8192,
            "scan_frequency_hours": 1,
            "retention_days": None,
        },
        "description": "Custom solutions for global-scale infrastructure.",
        "cta": "Talk to Expert",
        "display_features": [
            "Unlimited accounts & users",
            "Cloud+ connectors (SaaS/license/custom sources)",
            "Savings-proof exports for procurement cycles",
            "Custom feature development",
            "On-premise deployment options",
            "White-labeling support",
            "24/7/365 multi-region support",
        ],
    },
}
