from app.schemas.connections_aws_discovery import (
    AWSConnectionCreate,
    AWSConnectionResponse,
    AWSConnectionSetup,
    DiscoveredAccountResponse,
    TemplateResponse,
)
from app.schemas.connections_cloud_core import (
    AzureConnectionCreate,
    AzureConnectionResponse,
    GCPConnectionCreate,
    GCPConnectionResponse,
)
from app.schemas.connections_cloud_plus import (
    HybridConnectionCreate,
    HybridConnectionResponse,
    LicenseConnectionCreate,
    LicenseConnectionResponse,
    PlatformConnectionCreate,
    PlatformConnectionResponse,
    SaaSConnectionCreate,
    SaaSConnectionResponse,
)
from app.schemas.connections_common import (
    DiscoveryCandidateResponse,
    DiscoveryDeepScanRequest,
    DiscoveryStageARequest,
    DiscoveryStageResponse,
    _HYBRID_NATIVE_VENDORS,
    _LEDGER_NATIVE_VENDORS,
    _LICENSE_NATIVE_VENDORS,
    _PLATFORM_NATIVE_VENDORS,
    _SAAS_NATIVE_VENDORS,
    _normalize_non_empty,
)

__all__ = [
    "AWSConnectionCreate",
    "AWSConnectionResponse",
    "AWSConnectionSetup",
    "AzureConnectionCreate",
    "AzureConnectionResponse",
    "DiscoveryCandidateResponse",
    "DiscoveryDeepScanRequest",
    "DiscoveryStageARequest",
    "DiscoveryStageResponse",
    "DiscoveredAccountResponse",
    "GCPConnectionCreate",
    "GCPConnectionResponse",
    "HybridConnectionCreate",
    "HybridConnectionResponse",
    "LicenseConnectionCreate",
    "LicenseConnectionResponse",
    "PlatformConnectionCreate",
    "PlatformConnectionResponse",
    "SaaSConnectionCreate",
    "SaaSConnectionResponse",
    "TemplateResponse",
    "_HYBRID_NATIVE_VENDORS",
    "_LEDGER_NATIVE_VENDORS",
    "_LICENSE_NATIVE_VENDORS",
    "_PLATFORM_NATIVE_VENDORS",
    "_SAAS_NATIVE_VENDORS",
    "_normalize_non_empty",
]
