"""Command assembly for enterprise TDD gate."""

from __future__ import annotations

from scripts.enterprise_tdd_gate_config import (
    ANALYTICS_VISIBILITY_COVERAGE_FAIL_UNDER,
    ANALYTICS_VISIBILITY_COVERAGE_INCLUDE,
    ENFORCEMENT_COVERAGE_FAIL_UNDER,
    ENTERPRISE_GATE_COVERAGE_TARGETS,
    ENTERPRISE_GATE_TEST_TARGETS,
    LLM_COVERAGE_FAIL_UNDER,
    LLM_GUARDRAIL_COVERAGE_INCLUDE,
)
from scripts.enterprise_tdd_gate_optional_evidence import (
    append_optional_evidence_commands,
)


def build_gate_commands() -> list[list[str]]:
    pytest_cmd: list[str] = ["uv", "run", "pytest", "-q", "-o", "addopts="]
    pytest_cmd.extend(ENTERPRISE_GATE_TEST_TARGETS)
    pytest_cmd.extend(
        f"--cov={target}" for target in ENTERPRISE_GATE_COVERAGE_TARGETS
    )
    pytest_cmd.extend(
        [
            "--cov-report=xml:coverage-enterprise-gate.xml",
            "--cov-report=term-missing",
        ]
    )

    commands: list[list[str]] = [
        [
            "uv",
            "run",
            "python3",
            "scripts/verify_api_auth_coverage.py",
        ],
        [
            "uv",
            "run",
            "python3",
            "scripts/verify_env_hygiene.py",
        ],
        [
            "uv",
            "run",
            "python3",
            "scripts/verify_dependency_locking.py",
        ],
        [
            "env",
            "REGISTRY=ghcr.io/valdrics",
            "VERSION=0.0.0-enterprise-gate",
            "uv",
            "run",
            "python3",
            "scripts/verify_container_image_pinning.py",
        ],
        [
            "uv",
            "run",
            "python3",
            "scripts/verify_adapter_test_coverage.py",
        ],
        [
            "uv",
            "run",
            "python3",
            "scripts/verify_repo_root_hygiene.py",
        ],
        [
            "uv",
            "run",
            "python3",
            "scripts/verify_audit_report_resolved.py",
            "--allow-missing-report",
        ],
        [
            "uv",
            "run",
            "python3",
            "scripts/verify_test_to_production_ratio.py",
        ],
        [
            "uv",
            "run",
            "python3",
            "scripts/verify_python_module_size_budget.py",
            "--enforcement-mode",
            "strict",
        ],
        [
            "uv",
            "run",
            "python3",
            "scripts/verify_frontend_module_size_budget.py",
        ],
        [
            "uv",
            "run",
            "python3",
            "scripts/verify_alertmanager_channels.py",
            "--config-path",
            "prometheus/alertmanager.yml",
        ],
        [
            "uv",
            "run",
            "python3",
            "scripts/verify_alembic_head_integrity.py",
            "--migrations-path",
            "migrations/versions",
        ],
        [
            "uv",
            "run",
            "python3",
            "scripts/verify_jwt_bcp_checklist.py",
            "--checklist-path",
            "docs/security/jwt_bcp_checklist_2026-02-27.json",
        ],
        [
            "uv",
            "run",
            "python3",
            "scripts/verify_ssdf_traceability_matrix.py",
            "--matrix-path",
            "docs/security/ssdf_traceability_matrix_2026-02-25.json",
        ],
        [
            "uv",
            "run",
            "python3",
            "scripts/verify_enforcement_post_closure_sanity.py",
            "--doc-path",
            "docs/ops/enforcement_post_closure_sanity_2026-02-26.md",
            "--gap-register",
            "docs/ops/enforcement_control_plane_gap_register_2026-02-23.md",
        ],
        [
            "uv",
            "run",
            "python3",
            "scripts/verify_feature_enforceability_matrix.py",
            "--matrix-path",
            "docs/ops/feature_enforceability_matrix_2026-02-27.json",
        ],
        [
            "uv",
            "run",
            "python3",
            "scripts/verify_architecture_decision_records.py",
            "--docs-root",
            "docs/architecture",
        ],
        [
            "uv",
            "run",
            "python3",
            "scripts/verify_pkg015_launch_gate.py",
            "--gap-register",
            "docs/ops/enforcement_control_plane_gap_register_2026-02-23.md",
            "--matrix-path",
            "docs/ops/feature_enforceability_matrix_2026-02-27.json",
        ],
    ]

    append_optional_evidence_commands(commands)

    commands.extend(
        [
            [
                "uv",
                "run",
                "python3",
                "scripts/verify_enterprise_placeholder_guards.py",
                "--profile",
                "strict",
            ],
            pytest_cmd,
            [
                "uv",
                "run",
                "coverage",
                "report",
                '--include=app/modules/enforcement/*',
                f"--fail-under={ENFORCEMENT_COVERAGE_FAIL_UNDER}",
            ],
            [
                "uv",
                "run",
                "coverage",
                "report",
                f"--include={','.join(LLM_GUARDRAIL_COVERAGE_INCLUDE)}",
                f"--fail-under={LLM_COVERAGE_FAIL_UNDER}",
            ],
            [
                "uv",
                "run",
                "coverage",
                "report",
                f"--include={','.join(ANALYTICS_VISIBILITY_COVERAGE_INCLUDE)}",
                f"--fail-under={ANALYTICS_VISIBILITY_COVERAGE_FAIL_UNDER}",
            ],
        ]
    )
    return commands
