"""Generate a deterministic, local-only .env.dev from .env.example."""

from __future__ import annotations

import argparse
import base64
import hashlib
from pathlib import Path
import sys

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts.env_generation_common import render_env

DEFAULT_TEMPLATE_PATH = Path(".env.example")
DEFAULT_OUTPUT_PATH = Path(".env.dev")
DEFAULT_SEED = "valdrics-local-dev-seed-v1"


def _repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def _resolve_default_path(path: Path) -> Path:
    return (_repo_root() / path).resolve()


def _resolve_cli_path(path: Path) -> Path:
    raw = Path(path).expanduser()
    if raw.is_absolute():
        return raw.resolve()
    return (_repo_root() / raw).resolve()


def _protected_output_paths() -> set[Path]:
    repo_root = _repo_root()
    return {
        Path(__file__).resolve(),
        repo_root / ".env.example",
    }


def _ensure_output_parent_dir(output_path: Path) -> None:
    current = output_path.parent
    while True:
        if current.exists():
            if not current.is_dir():
                raise ValueError(
                    f"output_path parent must be a directory path: {current.as_posix()}"
                )
            return
        if current == current.parent:
            return
        current = current.parent


def _derive_digest(seed: str, key: str) -> bytes:
    return hashlib.sha256(f"{seed}:{key}".encode("utf-8")).digest()


def _derive_hex(seed: str, key: str, *, length: int = 64) -> str:
    material = hashlib.sha512(f"{seed}:{key}".encode("utf-8")).hexdigest()
    while len(material) < length:
        material += hashlib.sha512(material.encode("utf-8")).hexdigest()
    return material[:length]


def _derive_urlsafe_b64(seed: str, key: str) -> str:
    return base64.urlsafe_b64encode(_derive_digest(seed, key)).decode("utf-8")


def _derive_b64(seed: str, key: str) -> str:
    return base64.b64encode(_derive_digest(seed, key)).decode("utf-8")


def _build_overrides(seed: str) -> dict[str, str]:
    return {
        "APP_NAME": "Valdrics",
        "DEBUG": "false",
        "ENVIRONMENT": "local",
        "TESTING": "false",
        "API_URL": "http://localhost:8000",
        "FRONTEND_URL": "http://localhost:5174",
        "AWS_ASSUME_ROLE_TRUST_PRINCIPAL_ARN": (
            "arn:aws:iam::000000000000:role/ValdricsLocalDevControlPlane"
        ),
        "DATABASE_URL": "sqlite+aiosqlite:///./valdrics_local_dev.sqlite3",
        "DB_SSL_MODE": "disable",
        "LOCAL_SQLITE_BOOTSTRAP": "true",
        "ENABLE_SCHEDULER": "false",
        "REDIS_URL": "",
        "CSRF_SECRET_KEY": _derive_hex(seed, "CSRF_SECRET_KEY"),
        "ENCRYPTION_KEY": _derive_urlsafe_b64(seed, "ENCRYPTION_KEY"),
        "SUPABASE_JWT_SECRET": _derive_hex(seed, "SUPABASE_JWT_SECRET"),
        "KDF_SALT": _derive_b64(seed, "KDF_SALT"),
        "ADMIN_API_KEY": _derive_hex(seed, "ADMIN_API_KEY"),
        "INTERNAL_JOB_SECRET": _derive_hex(seed, "INTERNAL_JOB_SECRET"),
        "ENFORCEMENT_APPROVAL_TOKEN_SECRET": _derive_hex(
            seed, "ENFORCEMENT_APPROVAL_TOKEN_SECRET"
        ),
        "ENFORCEMENT_EXPORT_SIGNING_SECRET": _derive_hex(
            seed, "ENFORCEMENT_EXPORT_SIGNING_SECRET"
        ),
        "SUPABASE_URL": "https://local-dev.supabase.co",
    }

def _render_env(template_lines: list[str], overrides: dict[str, str]) -> str:
    rendered = render_env(template_lines, overrides)
    output_lines: list[str] = [
        "# Local deterministic development environment.",
        "# Generated by scripts/generate_local_dev_env.py; safe for isolated local sqlite development only.",
        "# Do not deploy this file to staging or production.",
        "",
    ]
    output_lines.extend(rendered.splitlines())
    return "\n".join(output_lines)


def generate_local_dev_env(
    *,
    template_path: Path,
    output_path: Path,
    seed: str,
) -> Path:
    if template_path.resolve() == output_path.resolve():
        raise ValueError("template_path and output_path must be different files")
    if output_path.resolve() in _protected_output_paths():
        raise ValueError(
            "output_path must not overwrite local-dev source or tracked template files"
        )
    if not template_path.exists():
        raise FileNotFoundError(f"Template file does not exist: {template_path.as_posix()}")
    if not template_path.is_file():
        raise ValueError(f"template_path must be a file: {template_path.as_posix()}")
    if output_path.exists() and not output_path.is_file():
        raise ValueError(f"output_path must be a file path: {output_path.as_posix()}")
    _ensure_output_parent_dir(output_path)
    rendered = _render_env(
        template_path.read_text(encoding="utf-8").splitlines(),
        _build_overrides(seed),
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(rendered, encoding="utf-8")
    return output_path


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Generate a deterministic .env.dev for local sqlite development. "
            "Values are intentionally non-production and safe for isolated local use."
        )
    )
    parser.add_argument(
        "--template-path",
        type=Path,
        default=DEFAULT_TEMPLATE_PATH,
        help="Path to source template file (default: .env.example).",
    )
    parser.add_argument(
        "--output-path",
        type=Path,
        default=DEFAULT_OUTPUT_PATH,
        help="Path for generated env file (default: .env.dev).",
    )
    parser.add_argument(
        "--seed",
        default=DEFAULT_SEED,
        help="Deterministic seed used for generated local-only values.",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _build_parser().parse_args(argv)
    template_path = _resolve_cli_path(args.template_path)
    output_path = _resolve_cli_path(args.output_path)
    output_path = generate_local_dev_env(
        template_path=template_path,
        output_path=output_path,
        seed=str(args.seed),
    )
    print(
        "[local-dev-env] ok "
        f"template={args.template_path.as_posix()} output={output_path.as_posix()}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
