"""Generate a deterministic, local-only .env.compose.dev for docker compose development."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts.env_generation_common import (
    ensure_parent_dir as _ensure_parent_dir_shared,
    promote_staged_file as _promote_staged_file,
    protected_output_paths_from_root as _protected_output_paths_from_root,
    render_env,
    repo_root_for as _repo_root_for,
    resolve_cli_path_from_root as _resolve_cli_path_from_root,
    stage_text_file as _stage_text_file,
)
from scripts.local_env_generation_shared import (
    derive_b64,
    derive_hex,
    derive_urlsafe_b64,
)

DEFAULT_TEMPLATE_PATH = Path(".env.example")
DEFAULT_OUTPUT_PATH = Path(".env.compose.dev")
DEFAULT_SEED = "valdrics-local-compose-seed-v1"


def _repo_root() -> Path:
    return _repo_root_for(__file__)


def _resolve_cli_path(path: Path, *, field_name: str) -> Path:
    return _resolve_cli_path_from_root(_repo_root(), path, field_name=field_name)


def _protected_output_paths() -> set[Path]:
    return _protected_output_paths_from_root(
        _repo_root(),
        __file__,
        ".env.example",
        ".env.dev",
        "docs/ops/feature_enforceability_matrix_2026-02-27.json",
        "docs/ops/key-rotation-drill-2026-02-27.md",
        "docs/ops/evidence/finance_guardrails_TEMPLATE.json",
        "docs/ops/evidence/README.md",
    )


def _ensure_output_parent_dir(output_path: Path) -> None:
    _ensure_parent_dir_shared(output_path, field_name="output_path")


def _stage_output_file(output_path: Path, rendered: str) -> Path:
    return _stage_text_file(output_path, rendered)


def _build_overrides(seed: str) -> dict[str, str]:
    postgres_password = derive_hex(seed, "POSTGRES_PASSWORD", length=48)
    return {
        "APP_NAME": "Valdrics",
        "DEBUG": "false",
        "ENVIRONMENT": "development",
        "TESTING": "false",
        "API_URL": "http://localhost:8000",
        "FRONTEND_URL": "http://localhost:3000",
        "ORIGIN": "http://localhost:3000",
        "CORS_ORIGINS": json.dumps(
            ["http://localhost:3000", "http://localhost:5174", "http://localhost:5173"],
            separators=(",", ":"),
        ),
        "AWS_ASSUME_ROLE_TRUST_PRINCIPAL_ARN": (
            "arn:aws:iam::000000000000:role/ValdricsLocalComposeControlPlane"
        ),
        "DATABASE_URL": (
            f"postgresql+asyncpg://postgres:{postgres_password}@postgres:5432/valdrics"
        ),
        "DB_SSL_MODE": "disable",
        "ENABLE_SCHEDULER": "false",
        "REDIS_URL": "redis://redis:6379",
        "POSTGRES_DB": "valdrics",
        "POSTGRES_USER": "postgres",
        "POSTGRES_PASSWORD": postgres_password,
        "GRAFANA_PASSWORD": derive_hex(seed, "GRAFANA_PASSWORD", length=48),
        "CSRF_SECRET_KEY": derive_hex(seed, "CSRF_SECRET_KEY"),
        "ENCRYPTION_KEY": derive_urlsafe_b64(seed, "ENCRYPTION_KEY"),
        "SUPABASE_JWT_SECRET": derive_hex(seed, "SUPABASE_JWT_SECRET"),
        "KDF_SALT": derive_b64(seed, "KDF_SALT"),
        "ADMIN_API_KEY": derive_hex(seed, "ADMIN_API_KEY"),
        "INTERNAL_JOB_SECRET": derive_hex(seed, "INTERNAL_JOB_SECRET"),
        "INTERNAL_METRICS_AUTH_TOKEN": derive_hex(seed, "INTERNAL_METRICS_AUTH_TOKEN"),
        "ENFORCEMENT_APPROVAL_TOKEN_SECRET": derive_hex(
            seed, "ENFORCEMENT_APPROVAL_TOKEN_SECRET"
        ),
        "ENFORCEMENT_EXPORT_SIGNING_SECRET": derive_hex(
            seed, "ENFORCEMENT_EXPORT_SIGNING_SECRET"
        ),
        "SUPABASE_URL": "https://local-compose.supabase.co",
    }


def _render_env(template_lines: list[str], overrides: dict[str, str]) -> str:
    rendered = render_env(template_lines, overrides)
    output_lines: list[str] = [
        "# Local deterministic docker compose environment.",
        "# Generated by scripts/generate_local_compose_env.py; safe for isolated docker compose development only.",
        "# Use with: docker compose --env-file .env.compose.dev up -d",
        "# Do not deploy this file to staging or production.",
        "",
    ]
    output_lines.extend(rendered.splitlines())
    return "\n".join(output_lines)


def generate_local_compose_env(
    *,
    template_path: Path,
    output_path: Path,
    seed: str,
) -> Path:
    if template_path.resolve() == output_path.resolve():
        raise ValueError("template_path and output_path must be different files")
    if output_path.resolve() in _protected_output_paths():
        raise ValueError(
            "output_path must not overwrite local-compose source or tracked template files"
        )
    if not template_path.exists():
        raise FileNotFoundError(
            f"Template file does not exist: {template_path.as_posix()}"
        )
    if not template_path.is_file():
        raise ValueError(f"template_path must be a file: {template_path.as_posix()}")
    if output_path.exists() and not output_path.is_file():
        raise ValueError(f"output_path must be a file path: {output_path.as_posix()}")
    _ensure_output_parent_dir(output_path)
    rendered = _render_env(
        template_path.read_text(encoding="utf-8").splitlines(),
        _build_overrides(seed),
    )
    staged_output_path = _stage_output_file(output_path, rendered)
    _promote_staged_file(
        staged_output_path,
        output_path,
        cleanup_output_on_failure=True,
    )
    return output_path


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Generate a deterministic .env.compose.dev for local docker compose development. "
            "Values are intentionally local-only and must not be promoted."
        )
    )
    parser.add_argument(
        "--template-path",
        type=Path,
        default=DEFAULT_TEMPLATE_PATH,
        help="Path to source template file (default: .env.example).",
    )
    parser.add_argument(
        "--output-path",
        type=Path,
        default=DEFAULT_OUTPUT_PATH,
        help="Path for generated env file (default: .env.compose.dev).",
    )
    parser.add_argument(
        "--seed",
        default=DEFAULT_SEED,
        help="Deterministic seed used for generated local-only values.",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _build_parser().parse_args(argv)
    template_path = _resolve_cli_path(args.template_path, field_name="template_path")
    output_path = _resolve_cli_path(args.output_path, field_name="output_path")
    output_path = generate_local_compose_env(
        template_path=template_path,
        output_path=output_path,
        seed=str(args.seed),
    )
    print(
        "[local-compose-env] ok "
        f"template={args.template_path.as_posix()} output={output_path.as_posix()}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
