#!/usr/bin/env python3
"""Generate minimal staging/production Alembic migration env scaffolds."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys
from typing import Any

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts.env_generation_common import render_env


DEFAULT_OUTPUT_DIR = Path(".runtime")
PLACEHOLDER_PREFIX = "REPLACE_WITH_"
SUPPORTED_ENVIRONMENTS = ("staging", "production")
SUPPORTED_DB_SSL_MODES = ("disable", "require", "verify-ca", "verify-full")


def _placeholder(name: str) -> str:
    return f"{PLACEHOLDER_PREFIX}{name}"


def _default_database_url() -> str:
    return (
        "postgresql+asyncpg://REPLACE_WITH_DB_USER:"
        "REPLACE_WITH_DB_PASSWORD@REPLACE_WITH_DB_HOST:5432/postgres"
    )


def _template_lines() -> list[str]:
    return [
        "# Managed Alembic migration environment scaffold.",
        "# Generated by scripts/generate_managed_migration_env.py.",
        "# Source this file only for Alembic migration commands.",
        "",
        "ENVIRONMENT=production",
        "DATABASE_URL=",
        "DB_SSL_MODE=require",
        "DB_SSL_CA_CERT_PATH=",
    ]


def _build_overrides(
    *,
    environment: str,
    database_url: str | None,
    db_ssl_mode: str,
    db_ssl_ca_cert_path: str | None,
) -> dict[str, str]:
    normalized_db_ssl_mode = str(db_ssl_mode or "require").strip().lower()
    if normalized_db_ssl_mode not in SUPPORTED_DB_SSL_MODES:
        raise ValueError(
            "db_ssl_mode must be one of: " + ", ".join(SUPPORTED_DB_SSL_MODES)
        )

    return {
        "ENVIRONMENT": environment,
        "DATABASE_URL": database_url or _default_database_url(),
        "DB_SSL_MODE": normalized_db_ssl_mode,
        "DB_SSL_CA_CERT_PATH": db_ssl_ca_cert_path or "",
    }


def _migration_blockers(values: dict[str, str]) -> list[str]:
    blockers: list[str] = []
    database_url = str(values.get("DATABASE_URL", "") or "").strip()
    if not database_url or PLACEHOLDER_PREFIX in database_url:
        blockers.append("DATABASE_URL")

    db_ssl_mode = str(values.get("DB_SSL_MODE", "require") or "require").strip().lower()
    db_ssl_ca_cert_path = str(values.get("DB_SSL_CA_CERT_PATH", "") or "").strip()
    if db_ssl_mode in {"verify-ca", "verify-full"} and not db_ssl_ca_cert_path:
        blockers.append("DB_SSL_CA_CERT_PATH")

    return blockers


def _required_operator_input_keys(values: dict[str, str]) -> list[str]:
    required_keys = ["DATABASE_URL"]
    db_ssl_mode = str(values.get("DB_SSL_MODE", "require") or "require").strip().lower()
    if db_ssl_mode in {"verify-ca", "verify-full"}:
        required_keys.append("DB_SSL_CA_CERT_PATH")
    return required_keys


def generate_managed_migration_env(
    *,
    output_path: Path,
    report_path: Path,
    environment: str,
    database_url: str | None = None,
    db_ssl_mode: str = "require",
    db_ssl_ca_cert_path: str | None = None,
) -> dict[str, Any]:
    normalized_environment = str(environment or "").strip().lower()
    if normalized_environment not in SUPPORTED_ENVIRONMENTS:
        raise ValueError(
            "environment must be one of: " + ", ".join(SUPPORTED_ENVIRONMENTS)
        )

    overrides = _build_overrides(
        environment=normalized_environment,
        database_url=database_url,
        db_ssl_mode=db_ssl_mode,
        db_ssl_ca_cert_path=db_ssl_ca_cert_path,
    )
    rendered = render_env(_template_lines(), overrides)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(rendered, encoding="utf-8")

    blockers = _migration_blockers(overrides)
    report = {
        "environment": normalized_environment,
        "output_path": output_path.as_posix(),
        "required_operator_input_keys": _required_operator_input_keys(overrides),
        "migration_validation_blockers": blockers,
        "migration_ready": not blockers,
        "validation_command": (
            "uv run python scripts/validate_migration_env.py "
            f"--env-file {output_path.as_posix()}"
        ),
        "migration_command": (
            f"set -a && source {output_path.as_posix()} && uv run alembic upgrade head"
        ),
    }
    report_path.parent.mkdir(parents=True, exist_ok=True)
    report_path.write_text(json.dumps(report, indent=2, sort_keys=True), encoding="utf-8")
    return report


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Generate a managed Alembic migration env scaffold for staging or production."
        )
    )
    parser.add_argument(
        "--environment",
        required=True,
        choices=SUPPORTED_ENVIRONMENTS,
        help="Target environment to scaffold.",
    )
    parser.add_argument(
        "--output-path",
        type=Path,
        default=None,
        help="Path for generated env file (default: .runtime/<environment>.migrate.env).",
    )
    parser.add_argument(
        "--report-path",
        type=Path,
        default=None,
        help=(
            "Path for generated JSON report "
            "(default: .runtime/<environment>.migrate.report.json)."
        ),
    )
    parser.add_argument("--database-url", default=None)
    parser.add_argument(
        "--db-ssl-mode",
        default="require",
        choices=SUPPORTED_DB_SSL_MODES,
    )
    parser.add_argument("--db-ssl-ca-cert-path", default=None)
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _build_parser().parse_args(argv)
    output_path = args.output_path or (
        DEFAULT_OUTPUT_DIR / f"{args.environment}.migrate.env"
    )
    report_path = args.report_path or (
        DEFAULT_OUTPUT_DIR / f"{args.environment}.migrate.report.json"
    )
    report = generate_managed_migration_env(
        output_path=output_path.resolve(),
        report_path=report_path.resolve(),
        environment=str(args.environment),
        database_url=args.database_url,
        db_ssl_mode=str(args.db_ssl_mode),
        db_ssl_ca_cert_path=args.db_ssl_ca_cert_path,
    )
    print(
        "[managed-migration-env] ok "
        f"environment={report['environment']} "
        f"output={report['output_path']} "
        f"migration_ready={report['migration_ready']} "
        f"blockers={len(report['migration_validation_blockers'])}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
